### PR TITLE
Updated ios setup instructions and added troubleshooting section for issues faced on Mac OS.

### PR DESCRIPTION
**Pull request by nchrisr**
This PR updates the ios setup instructions with steps that may be required for users on Mac OS with the M1 or M2 chip. It also includes a section with information for troubleshooting some issues that may be faced on Mac OS 14 or greater.

### CODE REVIEW

**Comment by mfazekas** [comment]
@nchrisr thanks much, but It doesn't make sense.

First the pod command is working for you, then
1.) why reinstall libffi for rosetta?
2.) why run pod under rosetta?

Also won't `npm run ios` execute pod install?

We can add a separate troubleshooting section, for pod repo update. But I don't want to add any `arch -x86_64`as that a sign of something wrong with your setup and instead fixing it, you workaround it.

**Comment by nchrisr** [comment]
@mfazekas 

1.) I don't think the pod command is working as it should for me. I'm not sure why the reinstall was needed, but that seemed to fix my issues.
2.) Not sure of the details but it works.

Were you able to test to see if you could reproduce the issue?

I created a fresh application using `npx react-native@latest init SampleProject`, and `npm run ios` did not seem to run pod install as my attempts to use `rnmapbox` kept failing.

Yes I can move the `pod repo update` to a troubleshooting section. 

There might be something wrong with my setup, but I think a workarounds section with this info would be useful So that someone running into this issue does not get stuck for hours like I did? I can dig further into this and try to figure out what the root cause in my setup is and update the docs with that as well. Thoughts?

**Comment by nchrisr** [comment]
@mfazekas So I have done some more investigation, and you were right, I had some major issues with my setup! I have updated the PR and removed the `arch -x86_64` portions.

That said, I can confirm that running `npm run ios`, does not run `pod install`. I tried this with a new react native project and it needed to be run explicitly after updating the Podfile, so I think this should be left in there.

**Comment by mfazekas** [comment]
@nchrisr thanks much for trying `npm run iOS`  I've added pod install steps to the instructions.

 https://github.com/rnmapbox/maps-docs/commit/c0167b2019d6fe637be71dd4257c894645260086
 
 I really would like to keep installation page to minimal as lot of people skip steps even when it's small. 
 Also I don't really feel the need to give instruction on how to upgrade homebrew, isn't really @rnmapbox specific.

**Comment by nchrisr** [comment]
@mfazekas Understood, I just thought a troubleshooting sections would be useful. So do you suggest I close this PR then?

**Comment by mfazekas** [comment]
@nchrisr yeah sorry there are a lot of issues with in this description. Like it's not related to M2, people might not be using home-brew, etc. 

We can write to do pod repo update when the pod output shows that, but it's kind of redundand I think.

**Pull request closed without merging**
